CREATE DATABASE BDAPI

CREATE TABLE CATEGORIA(
ID_CATEGORIA INT PRIMARY KEY IDENTITY(1,1),
DESCRIPCION VARCHAR(50)
)

CREATE TABLE PRODUCTO(
ID_PRODUCTO INT PRIMARY KEY IDENTITY(1,1),
CODIGO_BARRA VARCHAR(20),
DESCRIPCION VARCHAR(50),
MARCA VARCHAR(50),
ID_CATEGORIA INT,
PRECIO DECIMAL(10,2)
CONSTRAINT FK_IDCATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA)
)

INSERT INTO CATEGORIA(DESCRIPCION) VALUES ('Tecnologia'),('ElectroHogar'),('Accesorios');

INSERT INTO PRODUCTO(CODIGO_BARRA, DESCRIPCION, MARCA, ID_CATEGORIA, PRECIO) VALUES 
('55555555', 'Monitor Aoc 55"','AOC', 1,1200),
('400000', 'Toshiba andibook', 'WINDY', 2, 1749)